name: "💡 Feature"
description: Create an issue for a new feature
title: "💡 [FEATURE] - <title>"
labels: [
  "feature"
]
body:
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "The priority of this issue"
      options:
        - "Low"
        - "Medium"
        - "High"
    validations:
      required: true
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: "Start of development"
      placeholder: "month/day/year"
    validations:
      required: false
  - type: input
    id: end_date
    attributes:
      label: "End Date"
      description: "Estimated end of development"
      placeholder: "month/day/year"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: "Common issues"
      placeholder: "#Issues' IDs"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Provide a brief explanation of the feature"
      placeholder: "Summarise in a few lines your intended feature."
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "What are the dependencies of your feature ?"
      placeholder: "Identify the dependencies of this issue (what needs to be completed before this issue can be achieved)."
    validations:
      required: false
  - type: textarea
    id: feeds_into
    attributes:
      label: "Feeds Into"
      description: "What does this issue feed into ?"
      placeholder: "Identify anything this issue will be used for in the future/feeds into."
    validations:
      required: false

