name: Deploy to AWS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          scripts: |
            cd /home/ubuntu/2025-SecondhandMarketplace2/backend
            git pull origin dev
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart marketplace
            sudo systemctl status marketplace --no-pager
